export const GET_ALL_USER_DESIGNS = "GET_ALL_USER_DESIGNS"
export const GET_ALL_USER_DESIGNS_SUCCESS = "GET_ALL_USER_DESIGNS_SUCCESS"
export const USER_SIGNUP = "USER_SIGNUP"
export const USER_LOGIN = "USER_LOGIN"